default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anydime_development
  username: chris
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: anydime_test
  username: chris
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: safedime_production
  username: safedime
  password: <%= ENV["SAFEDIME_DATABASE_PASSWORD"] %>